name: Generate Dependencies CSV

on: workflow_dispatch

jobs:
  generate-dependencies-csv:
    runs-on: ubuntu-20.04
    name: Genereate a list of dependencies for this repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
        
      - name: Truncate Plan
        id: truncate-plan
        run: echo '::set-output name=plan::${${{ env.REPOSITORY_NAME }}:0:3}'

      - name: Test truncate output
        run: echo ${{ steps.truncate-plan.outputs.plan }}
