name: Generate Dependencies CSV

on: workflow_dispatch

jobs:
  generate-dependencies-csv:
    runs-on: ubuntu-20.04
    name: Genereate a list of dependencies for this repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Output
        id: set-output
        run: echo "::set-output name=plan::\"Hello\""
        shell: bash
        
      - name: Truncate Plan
        id: truncate-plan
        run: |
          stuff='${{ steps.set-output.outputs.plan }}'
          echo "::set-output name=plan::${stuff:0:5}"

      - name: Test truncate output
        run: echo '${{ steps.truncate-plan.outputs.plan }}'
        shell: bash
